/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPoIndexRouteImport } from './routes/_authenticated/po/index'
import { Route as AuthenticatedPoNewRouteImport } from './routes/_authenticated/po/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoIndexRoute = AuthenticatedPoIndexRouteImport.update({
  id: '/po/',
  path: '/po/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoNewRoute = AuthenticatedPoNewRouteImport.update({
  id: '/po/new',
  path: '/po/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/po/new': typeof AuthenticatedPoNewRoute
  '/po/': typeof AuthenticatedPoIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/po/new': typeof AuthenticatedPoNewRoute
  '/po': typeof AuthenticatedPoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/po/new': typeof AuthenticatedPoNewRoute
  '/_authenticated/po/': typeof AuthenticatedPoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/products' | '/settings' | '/po/new' | '/po/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/products' | '/settings' | '/' | '/po/new' | '/po'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/products'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/po/new'
    | '/_authenticated/po/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/po/': {
      id: '/_authenticated/po/'
      path: '/po'
      fullPath: '/po/'
      preLoaderRoute: typeof AuthenticatedPoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/po/new': {
      id: '/_authenticated/po/new'
      path: '/po/new'
      fullPath: '/po/new'
      preLoaderRoute: typeof AuthenticatedPoNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPoNewRoute: typeof AuthenticatedPoNewRoute
  AuthenticatedPoIndexRoute: typeof AuthenticatedPoIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPoNewRoute: AuthenticatedPoNewRoute,
  AuthenticatedPoIndexRoute: AuthenticatedPoIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
